spring.application.name=api-gateway
server.port=8761
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8760/eureka/
# 暴露所有端点（生产环境建议按需开放）
management.endpoints.web.exposure.include=*

# 显示健康检查的详细信息
management.endpoint.health.show-details=always

